#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

env = DefaultEnvironment().Clone()

sources = [
    'setup.py',
    'requirements.txt',
    'contrail_nova_networkapi/__init__.py',
    'contrail_nova_networkapi/api.py',
]

sdist_gen = env.Command('dist', sources,
                        'cd ' + Dir('.').path + ' && python setup.py sdist')
env.Default(sdist_gen)
env.Alias('contrail-nova-networkapi', sdist_gen)

if 'install' in BUILD_TARGETS:
    cmd = 'cd ' + Dir('.').path + ' && python setup.py install %s'
    env.Alias('install',
              env.Command(None, sources, cmd % env['PYTHON_INSTALL_OPT']))
